### ISSUE TITLE
Update from 5.1.11 to 6.02 is failing

### ISSUE THREAD

**Issue by Marty56** [dfigus/addon-tvheadend#296]
- ## The Problem

I tried to update to version 6.02.
Tvheadend stops working. I even cannot open the WebUI anymore.

## Environment

- Addon version: 6.02
- HA OS version: latest
- Installation methode: HA OS/Supervised
- Hardware:  generic x86_64, etc.

## Logs

See attachment
[dae55a80_tvheadend_2024-11-20T11-08-27.623Z.log](https://github.com/user-attachments/files/17829583/dae55a80_tvheadend_2024-11-20T11-08-27.623Z.log)

## Additional Information
I have note this behavior since version 6.x was first published.
Fortunately I could recover to 5.1 by using the restore function.

**Comment by dfigus** [comment]
Thanks for using my addon! I had a look into your logs and due to the updated TVHeadend version, TVHeadend runs a config migration at startup - and default is to create a backup upfront which can take multiple minutes depending on the size of your configuration (I had one instance with > 30 min on my installation). Here are the relevant log entries:

```
2024-11-20 12:05:28.708 [   INFO] config: backup: migrating config from 4.3-2323~g73a6bd00d-dirty (running 4.3-2374~g26ec161fb-dirty)
2024-11-20 12:05:28.708 [   INFO] config: backup: running, output file /config/tvheadend/backup/4.3-2323~g73a6bd00d-dirty.tar.bz2
2024-11-20 12:05:28.710 [   INFO] spawn: Executing "/bin/tar"
```

As long as the migration is running, you cannot use TVHeadend. However you can disable the automatic backup (this is what usually takes time) as described in my [docs](https://github.com/dfigus/addon-tvheadend/blob/main/tvheadend/DOCS.md#option-args) in case you do regular addon backups (e.g. before updating to the newest version). I'm also running it with the `--nobackup`.
